### PR TITLE
CSEC-16880 Scoped the blitz package to prevent dependency confusion

### PR DESCRIPTION
**Pull request by Enteris**
Scoping the blitz package to prevent dependency confusion in the UI module

### CODE REVIEW

**Review by GermainBergeron — APPROVED** [review]

**Comment by louis-bompart** [comment]
lockfiles should be regenerated tho

**Review by louis-bompart — COMMENTED** [review]
Install all the dependencies > yarn install

**Comment by Enteris** [comment]
The amount of warning is scary : 
```
jabeaumont@WKS-001490:~/repository/blitz2021$ yarn install
yarn install v1.22.18
info No lockfile found.
[1/4] Resolving packages...
warning lerna > @lerna/add > @evocateur/pacote@9.6.5: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/create > @evocateur/pacote@9.6.5: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/publish > @evocateur/pacote@9.6.5: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/bootstrap > read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
warning lerna > @lerna/publish > @evocateur/npm-registry-fetch@4.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/add > @evocateur/pacote > @evocateur/npm-registry-fetch@4.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/publish > @lerna/npm-dist-tag > @evocateur/npm-registry-fetch@4.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/publish > @evocateur/libnpmaccess@3.1.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/publish > @evocateur/libnpmaccess > @evocateur/npm-registry-fetch@4.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/version > temp-write > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning lerna > @lerna/publish > @lerna/npm-publish > @evocateur/libnpmpublish@1.2.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/publish > @lerna/npm-publish > @evocateur/libnpmpublish > @evocateur/npm-registry-fetch@4.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning lerna > @lerna/bootstrap > @lerna/symlink-dependencies > @lerna/create-symlink > @zkochan/cmd-shim > mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
warning lerna > @lerna/bootstrap > @lerna/run-lifecycle > npm-lifecycle > node-gyp > request > har-validator@5.1.5: this library is no longer supported
warning lerna > @lerna/create > globby > fast-glob > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning lerna > @lerna/create > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning lerna > @lerna/create > globby > fast-glob > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning lerna > @lerna/create > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @germainbergeron/blitz2021 > @types/winston@2.4.4: This is a stub types definition. winston provides its own type definitions, so you do not need this installed.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler@1.12.5: Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @germainbergeron/blitz2021 > libhoney > superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @germainbergeron/blitz2021 > aws-sdk > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @germainbergeron/blitz2021 > aws-sdk > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > @parcel/watcher > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @germainbergeron/blitz2021 > libhoney > superagent > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > @parcel/watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > babylon-walk > babel-runtime > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > htmlnano > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > htmlnano > uncss > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @germainbergeron/blitz2021 > jest > @jest/core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > cssnano > cssnano-preset-default > postcss-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > htmlnano > uncss > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning workspace-aggregator-3e0514e4-f3a0-46f1-8406-2821239a01c0 > @coveo/blitz-ui > parcel-bundler > htmlnano > uncss > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "lerna > @lerna/version > @lerna/github-client > @octokit/rest > @octokit/plugin-request-log@1.0.4" has unmet peer dependency "@octokit/core@>=3".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 11.44s.
jabeaumont@WKS-001490:~/repository/blitz2021$
```

**Comment by louis-bompart** [comment]
This would require moving out from Lerna or waiting for the new owners to update the stuff, both take time.

However, due to the nature of the project, this is a very very low priority problem I think.
IMO, at the current time, ain't worth spending any more breath on that.

LGTM :shipit:

**Pull request merged**
